[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
httparse = "1.10.1"
chrono = "0.4.41"
mime_guess = "2.0.5"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"